Broker: amqp://guest:guest@localhost:5672//
Result Backend: redis://localhost:6379/0
 
 -------------- celery@dhcp-10-22-132-180.wlan.ntnu.no v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.0.1-arm64-arm-64bit 2025-03-04 16:36:50
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         multi_agent_system:0x104446490
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> --loglevel=info  exchange=--loglevel=info(direct) key=--loglevel=info
                

[2025-03-04 16:36:50,264: WARNING/MainProcess] /Users/adamds/Library/Caches/pypoetry/virtualenvs/projectdeux-drlyUxii-py3.11/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-04 16:36:50,277: WARNING/MainProcess] /Users/adamds/Library/Caches/pypoetry/virtualenvs/projectdeux-drlyUxii-py3.11/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-04 16:36:51,318: WARNING/MainProcess] /Users/adamds/Library/Caches/pypoetry/virtualenvs/projectdeux-drlyUxii-py3.11/lib/python3.11/site-packages/kombu/pidbox.py:72: UserWarning: A node named celery@dhcp-10-22-132-180.wlan.ntnu.no is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))


worker: Warm shutdown (MainProcess)
2025-03-04 16:38:07,531 - INFO - Flushed system logs to logs/system_log_20250304_163649.json
[2025-03-04 16:38:07,531: INFO/MainProcess] Flushed system logs to logs/system_log_20250304_163649.json
2025-03-04 16:38:07,531 - INFO - Flushed interaction logs to logs/interaction_log_20250304_163649.json
[2025-03-04 16:38:07,531: INFO/MainProcess] Flushed interaction logs to logs/interaction_log_20250304_163649.json
2025-03-04 16:38:07,532 - INFO - Flushed LiteLLM logs to logs/litellm_log_20250304_163649.json
[2025-03-04 16:38:07,532: INFO/MainProcess] Flushed LiteLLM logs to logs/litellm_log_20250304_163649.json
[2025-03-04 16:38:07,532: WARNING/MainProcess] Flushing GLOBAL_LOG_DATA: {'run_id': '20250304_163649', 'agents': {}}
[2025-03-04 16:38:07,532: WARNING/MainProcess] Flushed logs to logs/litellm_log_20250304_163649.json
